Java-Funiture-OnlineShop/build.gradle, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/Option.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/OptionController.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/OptionRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/OptionResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/OptionService.java
=> Option directory

Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/ProductService.java
=> [UPDATE] 상품의 추가 기능 구현

Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/user/StringArrayConverter.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/user/User.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/user/UserRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/user/UserService.java
회원(User) 엔티티 생성 및 관련 컨트롤러, 서비스, 레포지토리 생성
=> [CREATE] 회원 생성

Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/Option.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/OptionController.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/OptionResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/option/OptionService.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/ProductRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/product/ProductService.java
=> [UPDATE] 옵션 CRUD

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/Cart.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/Option.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionService.java
FunitureOnlineShop -> funitureOnlineShop
=> [FIX] 패키지명 대소문자 수정

Java-Funiture-OnlineShop/build.gradle, Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/user/UserRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/GeneralExceptionHandler.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/GeneralValidationHandler.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception400.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception401.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception403.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception404.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception500.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/CustomUserDetails.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/CustomUserDetailsService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/JwtAuthenticationFilter.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/JwtTokenProvider.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/utils/ApiUtils.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/utils/FilterResponseUtils.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/StringArrayConverter.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/User.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java
회원가입 기능 추가, core의 import 및 package 수정, 회원가입용 DTO 생성
=> [UPDATE] 회원가입 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/core/security/Blacklist.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/JwtTokenProvider.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java
로그아웃 기능 추가, 토큰 블랙리스트 생성 및 토큰 무효화 추가
=> [UPDATE] 로그아웃 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/FunitureOnlineShop/user/UserRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/GeneralExceptionHandler.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/GeneralValidationHandler.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception400.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception401.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception403.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception404.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception500.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/CustomUserDetails.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/CustomUserDetailsService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/JwtAuthenticationFilter.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/JwtTokenProvider.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/utils/ApiUtils.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/utils/FilterResponseUtils.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/StringArrayConverter.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/User.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java
상품의 기능 수정 추가
패키지의 대소문자 추가 이슈로 인하여 전체적인 오류 수정
=> [UPDATE/FIX] 상품 수정 기능 + 패키지 오류 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
=> [UPDATE] 상품 삭제 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductComment.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java
상품평(ProductComment) 엔티티 생성 및 관련 컨트롤러, 서비스, 레포지토리 생성
=> [CREATE] 상품평 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/Coupon.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponService.java
쿠폰(Coupon) 엔티티 생성 및 관련 컨트롤러, 서비스, 레포지토리 생성
=> [CREATE] 쿠폰 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/Board.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardDTO.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardComment/BoardComment.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardComment/BoardCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardComment/BoardCommentDTO.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardComment/BoardCommentRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardComment/BoardCommentService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardFile/BoardFile.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardFile/BoardFileDTO.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardFile/BoardFileRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java
=> [CREATE] 보드관련 패키지생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardDTO.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardFile/BoardFile.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardFile/BoardFileRepository.java
=> [UPDATE] 보드 저장 및 읽기 기능

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/item/Item.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/item/ItemRepository.java
=> [CREATE] Order폴더 및 파일 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/Board.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/BoardFile/BoardFileRepository.java
=> [UPDATE] 보드 업데이트 및 삭제 기능

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception500.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProduct.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProductRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
Exception500의 불필요한 개행 제거, 이미지를 등록함으로써 함수들의 로직들 수정
=> [CREATE] 상품 이미지 등록 기능 구현

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/Coupon.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponService.java
=> [UPDATE] 쿠폰 저장 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/GeneralExceptionHandler.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/error/exception/Exception422.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/User.java
쿠폰을 하나씩 한 회원에게 분배하는 기능, 같은 쿠폰 중복 소유 불가, 남은 쿠폰이 없을 경우의 예외처리
=> [UPDATE] 쿠폰 분배 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/Category.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java
=> [CREATE] 카테고리 저장 기능 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponService.java
=> [UPDATE] 단일 쿠폰 삭제 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
상품 클래스 파일들의 Category의 import 경로 지정
=> [FIX] 카테고리 import 경로 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/coupon/CouponService.java
=> [UPDATE] 동일 쿠폰들 삭제 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java
등록된 카테고리의 ID를 조회해 특정 상품 찾기, 등록된 카테고리들 조회
=> [UPDATE] 카테고리 찾기 기능 구현

memoir/23.12.14/README.md
송한올 -> `orderCheck` 지원, HomeController 의 설명 추가
=> [DOCS] (4) 12.14 스크럼 기록 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
=> [CREATE] 홈컨트롤러 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/Category.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java
카테고리 저장 로직 수정
카테고리 전체 탐색 로직 수정
단일 카테고리 탐색에서 상하위 카테고리 탐색으로 수정
=> [FIX] 카테고리 저장 및 탐색 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
전체상품목록 / {카테고리} 메뉴를 둠으로써 클릭시 각 이름에 맞는 기능 구현
=> [CREATE] 홈 컨트롤러 구현 및 상품 찾기 기능 구현

Java-Funiture-OnlineShop/src/main/resources/templates/allProductPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/productCategoryPage.html
홈컨트롤러 메소드들의 리턴값으로 있는 html 파일 생성
=> [CREATE] VIEW 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java
=> [FIX] 상품 매핑방식 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java
=> [UPDATE] 카테고리 수정 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java
=> [UPDATE] 카테고리 삭제

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
=> [FIX] 상품 서비스 로직 변경

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java
=> [UPDATE] 회원탈퇴

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
장바구니에 상품이 담겨있다면 담겨있는 상품들을 보여주고 없다면 메시지 출력
=> [UPDATE] 홈컨트롤러 장바구니 페이지 구현

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProduct.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
=> [UPDATE] 파일 업로드시 랜덤 UUID 사용 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProduct.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java
=> [UPDATE] 보드 삭제 및 권한생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
=> [UPDATE] 홈컨트롤러 QNA 페이지 구현

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
=> [UPDATE] 홈컨트롤러 공지사항 기능 구현

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
=> [UPDATE] 홈 컨트롤러 유저 마이페이지 기능 구현

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
=> [FIX] 홈 컨트롤러의 장바구니 예외처리

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
=> [FIX] QNA와 공지사항 페이지의 예외처리 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
미로그인시 401에러, 그 이외의 오류는 500에러로 알려주며 e.getMessage() 를 통해 좀 더 자세한 파악 가능
=> [FIX] 마이페이지의 예외처리 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/payments/NicePayResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/payments/NicepayController.java, Java-Funiture-OnlineShop/src/main/resources/templates/payindex.html
=> [UPDATE] 페이먼트 로직생성

Java-Funiture-OnlineShop/src/main/resources/templates/cartPage.html
=> [CREATE]  카트페이지 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java
상품 페이지 입장 시 그 상품의 모든 후기를 가져오는 기능
=> [UPDATE] 상품의 전체 후기 탐색 기능 저장

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/commentFile/CommentFile.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheck.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java
회원의 권한 확인 후 상품 후기 삭제
결제 내역(orderCheck)이 옵션과 연관되도록 수정
결제 내역(orderCheck)이 선택 수량을 저장하도록 수정
=> [UPDATE] 상품 후기 삭제 기능 추가, [FIX] 결제 내역 일부 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/Cart.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/commentFile/CommentFile.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/commentFile/CommentFileDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/commentFile/CommentFileRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/Option.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheck.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheckRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductComment.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/resources/templates/cartPage.html
주문 후 수량 차감 및 주문 취소 후 수량 복구 기능 추가입니다
=> [UPDATE] 주문 후 수량변경

Java-Funiture-OnlineShop/src/main/resources/templates/orderPage.html
=> [CREATE] 오더페이지 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductComment.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java
상품 후기의 내용, 별점, 수정일 수정 및 이전 첨부파일 전부 삭제 후 재설정
=> [UPDATE] 상품 후기 수정 기능 추가

memoir/23.12.15/README.md
=> [DOCS] (5) 12.15 회고록 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java
=> [REFACT] Orderstatus 삭제

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java
=> [REFACT] 오더상태삭제

Java-Funiture-OnlineShop/src/main/resources/templates/index.html
디자인 수정
로그인, 회원가입, 로그아웃, 상품 페이지, 게시판 버튼 생성
=> [UPDATE] 메인 페이지 내용 생성

Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html
=> [CREATE] 공지사항 html

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardDTO.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html
=> [UPDATE] 공지사항 HTML 수정 및 카테고리 서비스, 컨트롤러 추가

Java-Funiture-OnlineShop/src/main/resources/static/js/custom.js, Java-Funiture-OnlineShop/src/main/resources/templates/cartPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderPage.html
=> [REFACT] CSS,자바스크립트 분리

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java, Java-Funiture-OnlineShop/src/main/resources/templates/login.html
로그인 화면 생성
로그인을 위한 LoginDto 생성 및 사용
=> [UPDATE] 로그인 화면 생성

Java-Funiture-OnlineShop/src/main/resources/templates/join.html
회원가입 화면 생성
아이디(이메일), 비밀번호, 이름, 전화번호, 주소를 받고 DB에 저장
=> [UPDATE] 회원가입 화면 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/Option.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java, Java-Funiture-OnlineShop/src/main/resources/static/js/custom.js, Java-Funiture-OnlineShop/src/main/resources/templates/cartPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/join.html, Java-Funiture-OnlineShop/src/main/resources/templates/login.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderPage.html
=> [FIX] 옵션 수량 이름 변경

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/item/Item.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java
=> [FIX] 옵션 변수명 변경으로 인한 수정

Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
별점들의 평균값, 장바구니 상품 추가, 상품리뷰 작성 추가, 상품리뷰 이미지 업로드 추가, 상품리뷰 이미지 제한 10개 추가
=> [CREATE] 상품페이지 HTML 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java
=> [FIX] 보드 불필요 코드 삭제

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
createboard / login / paycancel / payindex / payresponse / productPage
=> [UPDATE] 홈 컨트롤러 뷰 연결 메소드 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/User.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java, Java-Funiture-OnlineShop/src/main/resources/templates/index.html
포인트 삭제, 관리자 회원가입 삭제(미리 저장), Dto 정보 수정, 로그아웃 응답 수정
=> [FIX] USER 일부 기능 수정 및 예외 처리

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [FIX] 상품 상세 페이지 리뷰수정 및 옵션추가

Java-Funiture-OnlineShop/src/main/resources/templates/myPage.html
=> [CREATE] 회원 정보 뷰 생성

Java-Funiture-OnlineShop/build.gradle, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/utils/ModelMapperConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCategoryPage.html
의존성 ModelMapper 추가 / 카테고리별 상품 찾는 서비스 로직 추가
=> [UPDATE] 카테고리별 상품목록 페이지 추가

Java-Funiture-OnlineShop/src/main/resources/templates/orderPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderdetail.html
[CREATE] 주문내역페이지 생성, [FIX] 주문 페이지 수정
=> [CREATE] 주문내역페이지 [FIX] 생성

Java-Funiture-OnlineShop/build.gradle, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/utils/ModelMapperConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/allProductPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/myPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticedetail.html, Java-Funiture-OnlineShop/src/main/resources/templates/productCategoryPage.html
=> [UPDATE] 삭제,수정 어드민 권한 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheckDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productReview.html
=> [CREATE] 상품후기 작성 뷰 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionController.java, Java-Funiture-OnlineShop/src/main/resources/templates/orderPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderdetail.html
=> [FIX] 옵션 저장 경로 변경

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html
상품 먼저 선 생성시 해당 상품에 대한 상품 옵션 생성 가능
=> [CREATE] 상품 생성 뷰 페이지

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java
=> [UPDATE] 홈컨트롤러 로그인 경로 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java
@PreAuthorize("hasRole('ROLE_ADMIN')") 어노테이션 추가
=> [UPDATE] 상품 생성 수정 삭제기능 권한 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheckDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/productReview.html
=> [UPDATE] 상품페이지 옵션 재고 상태 업데이트

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/productUpdate.html
해당 상품의 정보를 불러와 텍스트박스안에 자동으로 기입됨 / 각각 삭제버튼과 수정버튼이 존재하며 옵션은 신규 생성 버튼또한 존재
=> [CREATE] 상품 수정 뷰 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentResponse.java, Java-Funiture-OnlineShop/src/main/resources/templates/commentUpdate.html
=> [CREATE] 상품 후기 수정 뷰 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/categorycreate.html
=> [CREATE] 카테고리 생성 HTML 및 홈 컨트롤러 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserController.java, Java-Funiture-OnlineShop/src/main/resources/templates/categoryUpdate.html
=> [CREATE] 카테고리 수정 삭제 뷰

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java, Java-Funiture-OnlineShop/src/main/resources/db/data.sql
=> [FIX] 일부 오류 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/myPage.html
내 정보 보기 뷰 이동 수정
내 정보 보기 뷰의 내용 수정
=> [FIX] 내 정보 보기 기능 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/Board.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardDTO.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/User.java, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html
=> [FIX] 게시판 HTML 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/Category.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java, Java-Funiture-OnlineShop/src/main/resources/templates/categoryUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/categorycreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/join.html
컨트롤러에서 값을 받아오는 방식 수정
Dto에서 생성자의 상위 카테고리 id 수정
서비스에서 update 방법 수정
카테고리 저장 뷰 및 수정/삭제 뷰 수정
=> [FIX] 카테고리 저장 및 수정/삭제의 오류 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html
=> [FIX] 상품 생성 뷰 수정중

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
=> [FIX] 상품 서비스 오류코드 삭제

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/Board.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardDTO.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html
=> [FIX] HTML 코드 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/Category.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/commentUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html, REST API/배준혁.md
=> [FIX] 상품 추가 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/application.yml, Java-Funiture-OnlineShop/src/main/resources/templates/categorycreate.html
카테고리가 대분류, 중분류, 소분류로만 존재하도록 변경
=> [FIX] 카테고리 생성 기능 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/application.yml, Java-Funiture-OnlineShop/src/main/resources/templates/allProductPage.html
SecutiryConfig 에 /product/save 설정
=> [FIX] 상품생성 권한설정 1차 수정중

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java
=> [FIX] 상품생성 권한 관리자에게만 부여 

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
제거된 종속성과 사용하지 않는 예외처리 클래스 등 제거
=> [UPDATE] 사용하지 않는 import문 제거

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java
=> [FIX] findProductsByCategory 메소드 수정

Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html
추가 생성 버튼 클릭시 정보가 남아있는 상태에서 disabled 되어있는것을 해제, reset 함
=> [UPDATE] 상품 생성뷰 추가생성 버튼 추가

Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html
옵션 저장 버튼, 상품 저장 버튼의 disabled 상태 변경
=> [FIX] 추가 생성버튼의 옵션의 상호작용 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html
=> [UPDATE] 상품 저장 뷰 완성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/Board.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/application.yml, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticedetail.html
RestController -> Controller로 변경
=> [FIX] Board 컨트롤러 및 HTML 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/DownloadController.java, Java-Funiture-OnlineShop/src/main/resources/application.yml, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticedetail.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticeupdate.html
=> [UPDATE] 보드디테일 HTML 코드 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticedetail.html
=> [UPDATE] 보드 업데이트 코드수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/Category.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/categoryUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/categorycreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/myPage.html
=> [HOTFIX] 브런치 복구

Java-Funiture-OnlineShop/src/main/resources/templates/categoryUpdate.html
=> [UPDATE] 카테고리 수정/삭제 뷰 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/Option.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionResponse.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [REFACT] 상품 상세 페이지 리빌딩

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/application.yml, Java-Funiture-OnlineShop/src/main/resources/db/data.sql, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html
=> [FIX] 상품 저장 시 카테고리도 저장1

Java-Funiture-OnlineShop/src/main/resources/application.yml
=> [FIX] Application.yml 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/resources/db/data.sql, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [FIX] 상품 상세 페이지 옵션 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/payments/NicepayController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/UserService.java, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticedetail.html
=> [UPDATE] 페이먼츠 로직 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/payments/NicepayController.java, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/payindex.html
=> [FIX] 게시글 생성 오류 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/menu.html
=> [UPDATE] 메뉴바 생성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProductRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/application.yml, Java-Funiture-OnlineShop/src/main/resources/db/data.sql, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
저장된 이미지의 UUID와 OriginalFileName 을 불러와서 상세페이지에 상품의 이미지 또한 보여지게 수정
=> [UPDATE] 상품 상세페이지 이미지 불러오기 기능 추가

Java-Funiture-OnlineShop/src/main/resources/templates/index.html
=> [UPDATE] 메뉴바 나오는 함수 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/Board/BoardService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/resources/templates/createboard.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticePage.html, Java-Funiture-OnlineShop/src/main/resources/templates/noticedetail.html
게시글 작성 시 토큰 확인과 파일 전송의 문제 해결
redirect 문제 해결
게시판 UI, UX 향상
=> [FIX] 게시글 작성 및 일부 오류 수정

Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [UPDATE] 상품 상세페이지 장바구니 추가 및 수량 기능 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/Cart.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/cart/CartService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/user/User.java, Java-Funiture-OnlineShop/src/main/resources/templates/cartPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
장바구니에 상품 추가 일부 오류 수정
현 로그인 회원 인증 문제
=> [FIX] 장바구니에 상품 추가 일부 오류 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCategoryPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [UPDATE] 카테고리별 상품 리스트 페이지

Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [UPDATE] 상품 상세페이지 가격 함수 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productCategoryPage.html
=> [FIX] 카테고리별 상품리스트 페이지 이미지 기능 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [UPDATE] 상세페이지 리뷰 세션 추가

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/Product.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productUpdate.html
=> [UPDATE] 상품 수정 뷰 초안

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [FIX] 상세페이지 리뷰 이슈 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheck.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheckDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheckRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/resources/db/data.sql, Java-Funiture-OnlineShop/src/main/resources/templates/commentUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/menu.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderdetail.html, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/productReview.html
주문 내역 보기 표 완성
상품 후기 작성 버튼
상품 후기 수정 버튼
상품 후기 삭제 버튼
상품 상세페이지에 상품후기 표시 수정 중
=> [UPDATE] 주문 내역 보기 및 상품 후기 작성

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/resources/templates/productUpdate.html
카테고리 정보 불러오기, 받아오기
받아온 카테고리 정보를 토대로 상품 정보 받아오기 불러오기
받아온 상품 정보를 토대로 옵션 받아오기 불러오기
이미지 추가 삭제
옵션 추가 삭제
상품 수정 삭제
=> [UPDATE] 상품 수정 페이지 기능들 추가

Java-Funiture-OnlineShop/src/main/resources/templates/orderPage.html
=> [FIX] 주문페이지 사용자 출력

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/Order.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderRequest.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/order/OrderService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheck.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/orderCheck/OrderCheckDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/payments/NicepayController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentResponse.java, Java-Funiture-OnlineShop/src/main/resources/db/data.sql, Java-Funiture-OnlineShop/src/main/resources/templates/returnorder.html
오더체크 연관매핑 수정입니다
option -> cart
이로 인해 다른 오더체크 사용하는 엔티티와 DTO 수정합니다
=> [FIX] 오더체크 연관매핑 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/commentFile/CommentFileDto.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/commentFile/CommentFileRepository.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/fileProduct/FileProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/home/HomeController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductResponse.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/productComment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/resources/templates/cartPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/commentUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/productPage.html
=> [FIX] 상품 후기 목록 생성 수정 중

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/comment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/comment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/db/data.sql, Java-Funiture-OnlineShop/src/main/resources/templates/adminPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/categoryUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/categorycreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/commentCreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/commentUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/join.html, Java-Funiture-OnlineShop/src/main/resources/templates/login.html, Java-Funiture-OnlineShop/src/main/resources/templates/menu.html, Java-Funiture-OnlineShop/src/main/resources/templates/myPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderCheckPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/productCategoryPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/productDetail.html, REST API/배준혁.md
html 스타일 수정
상품 후기 삭제 수정
주문 내역 탐색 수정
=> [FIX] html 및 일부 서비스의 오류 수정

Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/category/CategoryController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/comment/ProductCommentController.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/comment/ProductCommentService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/core/security/SecurityConfig.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/option/OptionService.java, Java-Funiture-OnlineShop/src/main/java/com/example/funitureOnlineShop/product/ProductService.java, Java-Funiture-OnlineShop/src/main/resources/db/data.sql, Java-Funiture-OnlineShop/src/main/resources/templates/adminPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/boardDetail.html, Java-Funiture-OnlineShop/src/main/resources/templates/boardPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/categoryUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/categorycreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/commentCreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/commentUpdate.html, Java-Funiture-OnlineShop/src/main/resources/templates/index.html, Java-Funiture-OnlineShop/src/main/resources/templates/join.html, Java-Funiture-OnlineShop/src/main/resources/templates/login.html, Java-Funiture-OnlineShop/src/main/resources/templates/menu.html, Java-Funiture-OnlineShop/src/main/resources/templates/myPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/orderCheckPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/paycancel.html, Java-Funiture-OnlineShop/src/main/resources/templates/payindex.html, Java-Funiture-OnlineShop/src/main/resources/templates/productCategoryPage.html, Java-Funiture-OnlineShop/src/main/resources/templates/productChoose.html, Java-Funiture-OnlineShop/src/main/resources/templates/productCreate.html, Java-Funiture-OnlineShop/src/main/resources/templates/productDetail.html, Java-Funiture-OnlineShop/src/main/resources/templates/productUpdate.html, REST API/배준혁.md
=> [FIX] HTML 스타일 수정
